server:
  port: 9200

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///linyu?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username:
    password:
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: Asia/Shanghai
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 500MB
  redis:
    host:
    port:
    password:
  mail:
    host: smtp.163.com
    protocol: smtp
    default-encoding: UTF-8
    username:
    password:
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 587
            class: javax.net.ssl.SSLSocketFactory
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration

oauth2:
  github:
    client-id:
    client-secret:
    redirect-uri: http://localhost:9200/v1/api/oauth2/github/callback
  # 添加前端URL配置
  frontend-url: http://localhost:5173/

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

voice:
  model: "/model/faster-whisper-small/"
  transitionApi: "http://123.207.210.163:8000/v1/audio/transcriptions"

rocketmq:
  enabled: true
  name-server:
  producer:
    group:
    send-message-timeout: 5000
    retry-times-when-send-failed: 3
    retry-times-when-send-async-failed: 3

minio:
  endpoint:
  bucketName: linyu
  fileBucketName: file
  accessKey:
  secretKey:


