server:
  port: 9200

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/linyu?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: Asia/Shanghai
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.163.com
    protocol: smtp
    default-encoding: UTF-8
    username: xxxx@163.com
    password: xxxxxx
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

voice:
  model: "/model/faster-whisper-small/"
  transitionApi: "http://123.207.210.163:8000/v1/audio/transcriptions"

rocketmq:
  enabled: false
  name-server: 127.0.0.1:9876
  producer:
    group: linyu_group
    send-message-timeout: 5000
    retry-times-when-send-failed: 3
    retry-times-when-send-async-failed: 3

minio:
  endpoint: http://127.0.0.1:9000
  bucketName: linyu
  fileBucketName: file
  accessKey: xxx
  secretKey: xxx
