version: '3.8'
networks:
  rocketmq:
    driver: bridge
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - /linyu/mysql:/var/lib/mysql

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - /linyu/redis:/data

  whisper:
    image: fedirz/faster-whisper-server:latest-cpu
    container_name: whisper
    ports:
      - "8000:8000"
    volumes:
      - /linyu/whisper/model:/model

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /linyu/minio:/data
    command: server /data --console-address ":9001"

  namesrv:
    image: apache/rocketmq:5.3.0
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    networks:
      - rocketmq
    command: sh mqnamesrv
    environment:
      - JAVA_OPT_EXT=-server -Xms128m -Xmx128m
  broker:
    image: apache/rocketmq:5.3.0
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
      - JAVA_OPT_EXT=-server -Xms128m -Xmx128m
    depends_on:
      - namesrv
    volumes:
      - ./broker.conf:/home/rocketmq/broker.conf
    networks:
      - rocketmq
    command: sh mqbroker -c /home/rocketmq/broker.conf

  linyu:
    image: henam/linyu:latest
    container_name: linyu
    depends_on:
      - mysql
      - redis
      - minio
      - whisper
      - namesrv
      - broker
    ports:
      - "9100:9100"
      - "9200:9200"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      ROCKET_NAME_SERVER: ${ROCKET_NAME_SERVER}